name: WarningManager
version: 1.0
description: Be in control of your players. Set warnings and punishments.
author: Synapz_
main: me.synapz.warnings.WarningManager
database: false

commands:
   warnings:
      description: Display the command menu.

permissions:
   warnings.*:
     description: Gives access to all AdminEssentials commands
     children:
       warnings.warn
       warnings.check
       warnings.reset
       warnings.help
       warnings.notify







